// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvftvswyrevummbvyhxa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2ZnR2c3d5cmV2dW1tYnZ5aHhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4OTU4NTUsImV4cCI6MjA2NjQ3MTg1NX0.Fxj47eYV6jz0SjyNSd4770ApYSY0_1MQZsZRrFZQ6cA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);